version: "3.7"

services:
  app:
    build: .
    init: true
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - "docker-compose_app.env"
    links:
      - db
    volumes:
      - ".:/usr/src/app"
    stdin_open: true
    command: bundle exec rails s -p 3000 -b 0.0.0.0

  db:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - "docker-compose_db.env"